version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.5-fpm-alpine
    volumes:
      - .:/var/www/html
    entrypoint: sh -c "chmod -R 777 /var/www/html/backend/logs && chmod -R 777 /var/www/html/backend/database && docker-php-entrypoint php-fpm"
