server {
    listen 80;
    index index.php index.html index.htm;
    root /var/www/html/backend/public;
    server_name localhost;

    client_max_body_size 10M;
    client_body_buffer_size 128k;
    client_body_timeout 10s;

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param CONTENT_TYPE $content_type;
        fastcgi_param CONTENT_LENGTH $content_length;
        fastcgi_param REQUEST_BODY $request_body;
    }
}
